server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
        maxHttpHeaderSize: 10240000
        maxHttpPostSize: 10240000 
    port: 8080
    maxHttpHeaderSize: 10240000
    maxHttpPostSize: 10240000
      
spring:
    application:
        name: easyNetty
    # 环境 dev|test|prod
    profiles:
       active: test
    devtools:
      restart:
        enabled: true
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    activiti:
        check-process-definitions: false
    freemarker:
        allowRequestOverride: false
        allowSessionOverride: false
        cache: true
        checkTemplateLocation: true
        contentType: text/html
        exposeRequestAttributes: false
        exposeSessionAttributes: false
        exposeSpringMacroHelpers: false
        suffix: .html
        templateEncoding: UTF-8
        #表示所有的模板文件都放在该目录下
        templateLoaderPath: classpath:/templates/ 
        locale: zh_CN
        date_format: yyyy-MM-dd
        time_format: HH:mm:ss
        datetime_format: yyyy-MM-dd HH:mm:ss        
        request-context-attribute: request
        settings:
          number_format: 0.##
          
#指定mvc视图的后缀.
    mvc:
        view:
            prefix: /views/
            suffix: .html
    #Jedis配置
    jedis :
        pool :
            host : 127.0.0.1
            port : 6379
            password : 123456
            timeout : 0
            config :
               maxTotal : 100
               maxIdle : 10
               maxWaitMillis : 100000
mybatis:
    mapper-locations: classpath*:org/easymis/easysaas/portal/entitys/mybatis/mapper/*Mapper.xml
    type-aliases-package: org.easymis.easysaas.portal.entitys.mybatis.dto
    configuration:
        map-underscore-to-camel-case: true
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    pageSizeZero: true
    params: count=countSql
