INSERT INTO "JSDEV"."JS_CARD_ACTION_CONFIG"("ID", "COMPANY_ID", "CMD", "CONFIG", "TPL", "PARAM_TYPE", "STATUS", "INTERFACE_URL", "COMPANY_NAME", "BODY_TYPE", "IS_DATA_SIGN", "SIGN_ALGORITHM", "SIGN_BODY", "CONTAIN_TYPE", "CONTAIN_RULE", "THIRD_PLATFORM") VALUES ('1', '92', 'senddata', '{
	"enable": "1",
	"isHttps": "0",
	"submit_url": "http://cn828.800app.com/uploadfile/staticresource/257790/269129/sy_AddLeads.aspx",
	"oid": "",
	"mKey": "",
	"data": {
		"VISITORSTATICID": "$CARD_STATICID",
		"REALNAME": "$CARD_REALNAME",
		"MOBILE": "$CARD_MOBILE",
		"NAME": "$CARD_NAME",
		"QQ": "$CARD_QQ",
		"MSN": "$CARD_WEIXIN",
		"CREATETIME": "$CARD_CREATETIME",
		"ALLOCATIONTIME": "$CARD_ALLOCATIONTIME",
		"CRMSTATE": "$CARD_STATE",
		"EXTCOLUMN8": "$CARD_COLUMN8",
		"EXTCOLUMN9": "$CARD_COLUMN9",
		"EXTCOLUMN10": "$CARD_COLUMN10",
		"NOTE": "$CARD_NOTE",
		"EXTCOLUMN1": "$CARD_COLUMN1",
		"RECORDS": "$CARD_RECORDS"
	}
}', '{
	"staticId": "$CARD_STATICID",
	"crm_holder": "$CARD_REALNAME",
	"crmzdy_80974415": "$CARD_MOBILE",
	"crm_name": "$CARD_NAME",
	"crmzdy_80974418": "$CARD_QQ",
	"crmzdy_88070094": "$CARD_WEIXIN",
	"crmzdy_88232342": "$CARD_CREATETIME",
	"crmzdy_88232295": "$CARD_ALLOCATIONTIME",
	"crmzdy_80979018": "$CARD_STATE",
	"crmzdy_81253707": "$CARD_COLUMN8",
	"crmzdy_88167326": "$CARD_COLUMN9",
	"crmzdy_80974439": "$CARD_COLUMN10",
	"crmzdy_80979020": "$CARD_NOTE",
	"crmzdy_88232306": "$CARD_COLUMN1",
	"crmzdy_88232317": "$CARD_RECORDS"
}', 'json', '1', 'http://cn828.800app.com/uploadfile/staticresource/257790/269129/sy_AddLeads.aspx', '客户92', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "JSDEV"."JS_CARD_ACTION_CONFIG"("ID", "COMPANY_ID", "CMD", "CONFIG", "TPL", "PARAM_TYPE", "STATUS", "INTERFACE_URL", "COMPANY_NAME", "BODY_TYPE", "IS_DATA_SIGN", "SIGN_ALGORITHM", "SIGN_BODY", "CONTAIN_TYPE", "CONTAIN_RULE", "THIRD_PLATFORM") VALUES ('86', '95', 'senddata', '{
							"enable": "1",
							"isHttps": "0",
							"submit_url": "",
							"oid": "",
							"mKey": "",
							"data": {
								"VISITORSTATICID": "$CARD_STATICID",
								"REALNAME": "$CARD_REALNAME",
								"MOBILE": "$CARD_MOBILE",
								"NAME": "$CARD_NAME",
								"QQ": "$CARD_QQ",
								"MSN": "$CARD_WEIXIN",
								"CREATETIME": "$CARD_CREATETIME",
								"ALLOCATIONTIME": "$CARD_ALLOCATIONTIME",
								"CRMSTATE": "$CARD_STATE",
								"EXTCOLUMN8": "$CARD_COLUMN8",
								"EXTCOLUMN9": "$CARD_COLUMN9",
								"EXTCOLUMN10": "$CARD_COLUMN10",
								"NOTE": "$CARD_NOTE",
								"EXTCOLUMN1": "$CARD_COLUMN1",
								"RECORDS": "$CARD_RECORDS"
							}
						}
  					', '{
"crm_name": "$CARD_NAME",
"crmzdy_80974413": "$CARD_SEX",
"crmzdy_80974415": "$CARD_MOBILE",
"crmzdy_80974418": "$CARD_QQ",
"crmzdy_88070094": "$CARD_WEIXIN",
"crmzdy_80974439": "$CARD_COLUMN10",
"crmzdy_80979020": "$CARD_REMARK",
"crmzdy_80974422": "$CARD_EDUCATION",
"crmzdy_80974432": "$CARD_LEVEL",
"crmzdy_88232360": "$CARD_BUSINESS_GROUP",
"crmzdy_88232371": "$CARD_CONTACTKEYWORD",
"crmzdy_88167326": "CARD_COLUMN9",
"crmzdy_81253707": "CARD_COLUMN8",
"crmzdy_80974437": "$CARD_INTENTION_CLASS",
"crmzdy_88232284": "$CARD_CREATE_USER_ID",
"crmzdy_88232342": "$CARD_CREATE_TIME",
"crm_holder": "$CARD_REALNAME",
"crmzdy_88232295": "$CARD_ALLOCATIONTIME",
"crmzdy_80979018": "$CARD_STATE",
"crmzdy_88232306": "$CARD_COLUMN1",
"crmzdy_88232317": "$CARD_RECORDS",
"crmzdy_88232948": "$CARD_STATICID",
"crmzdy_88232959": "$CARD_URL"
}', 'json', '1', 'http://cn828.800app.com/uploadfile/staticresource/257790/269129/sy_AddLeads.aspx', '测试95', 'json', NULL, 'MD5', NULL, NULL, NULL, NULL);
INSERT INTO "JSDEV"."JS_CARD_ACTION_CONFIG"("ID", "COMPANY_ID", "CMD", "CONFIG", "TPL", "PARAM_TYPE", "STATUS", "INTERFACE_URL", "COMPANY_NAME", "BODY_TYPE", "IS_DATA_SIGN", "SIGN_ALGORITHM", "SIGN_BODY", "CONTAIN_TYPE", "CONTAIN_RULE", "THIRD_PLATFORM") VALUES ('23', '90', 'senddata', '{
							"enable": "1",
							"isHttps": "0",
							"submit_url": "",
							"oid": "",
							"mKey": "",
							"data": {
								"VISITORSTATICID": "$CARD_STATICID",
								"REALNAME": "$CARD_REALNAME",
								"MOBILE": "$CARD_MOBILE",
								"NAME": "$CARD_NAME",
								"QQ": "$CARD_QQ",
								"MSN": "$CARD_WEIXIN",
								"CREATETIME": "$CARD_CREATETIME",
								"ALLOCATIONTIME": "$CARD_ALLOCATIONTIME",
								"CRMSTATE": "$CARD_STATE",
								"EXTCOLUMN8": "$CARD_COLUMN8",
								"EXTCOLUMN9": "$CARD_COLUMN9",
								"EXTCOLUMN10": "$CARD_COLUMN10",
								"NOTE": "$CARD_NOTE",
								"EXTCOLUMN1": "$CARD_COLUMN1",
								"RECORDS": "$CARD_RECORDS"
							}
						}
  					', '{
	"staticId": "$CARD_STATICID",
	"crm_holder": "$CARD_REALNAME",
	"crmzdy_80974415": "$CARD_MOBILE",
	"crm_name": "$CARD_NAME",
	"crmzdy_80974418": "$CARD_QQ",
	"crmzdy_88070094": "$CARD_WEIXIN",
	"crmzdy_88232342": "$CARD_CREATETIME",
	"crmzdy_88232295": "$CARD_ALLOCATIONTIME",
	"crmzdy_80979018": "$CARD_STATE",
	"crmzdy_81253707": "$CARD_COLUMN8",
	"crmzdy_88167326": "$CARD_COLUMN9",
	"crmzdy_80974439": "$CARD_COLUMN10",
	"crmzdy_80979020": "$CARD_NOTE",
	"crmzdy_88232306": "$CARD_COLUMN1",
	"crmzdy_88232317": "$CARD_RECORDS"
}', 'json', '1', 'http://cn828.800app.com/uploadfile/staticresource/257790/269129/sy_AddLeads.aspx', '客户90', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "JSDEV"."JS_CARD_ACTION_CONFIG"("ID", "COMPANY_ID", "CMD", "CONFIG", "TPL", "PARAM_TYPE", "STATUS", "INTERFACE_URL", "COMPANY_NAME", "BODY_TYPE", "IS_DATA_SIGN", "SIGN_ALGORITHM", "SIGN_BODY", "CONTAIN_TYPE", "CONTAIN_RULE", "THIRD_PLATFORM") VALUES ('70', '95', 'senddata', '{
	"enable": "1",
	"isHttps": "0",
	"submit_url": "http://test.cnxfu.com:8090/dataplatform/api/el/saveContact",
	"tpl": "ext.tpl",
	"app_username": "",
	"app_password": "",
	"ext": {
		"visitorStaticId": "$VISITOR_STATIC_ID",
		"name": "$CARD_NAME",
		"email": "$CARD_EMAIL",
		"mobile": "$CARD_PHONE",
		"qq": "$QQ",
		"chatId": "$CHATID",
		"sex": "$CARD_SEX",
		"note": "$CARD_NOTE",
		"companyName": "$CARD_COMPANY",
		"area": "$CARD_AREA",		
		"creater": "$CURRENT_CUSTOMERID",
		"personal": "$CURRENT_CUSTOMERID",
		"msn": "$CARD_MSN",
		"visitor_location_city":"$VISITOR_LOCATION_CITY",
		"visitor_location_province":"$VISITOR_LOCATION_PROVINCE",
		"visitor_location_country":"$VISITOR_LOCATION_COUNTRY",
		"firstUrl":"$FIRSTURL"
		}
}', '{
	"id": "$VISITOR_ID",
	"visitorStaticId": "$VISITOR_STATIC_ID",	
	"chatId": "$CHATID",	
	"mobile": "$CARD_PHONE",	
	"name": "$CARD_NAME",	
	"chatrecord":"$CHAT_RECORD_RESULT",
	"chatrecordJson":"$CHAT_JSRECORD_RESULT_BASE64",
	"area": "$CARD_AREA",	
	"remark": "$CARD_NOTE",	
	"url": "$CHATURL",	
	"email": "$CARD_EMAIL",
	"qq": "$QQ",
	"createrId": "$USERNAME",	
	"creater": "$USERNAME",	
	"createTime": "$CURRENT_DATETIME",	
	"personal": "$USERNAME",
	"keyword":"$KEYWORD",
	"city":"$VISITOR_LOCATION_CITY",
	"province":"$VISITOR_LOCATION_PROVINCE",
	"country":"$VISITOR_LOCATION_COUNTRY",
	"firstUrl":"$FIRSTURL",
	"wechat":"$CARD_MSN"
}', 'json', '1', 'http://test.cnxfu.com:8090/dataplatform/api/el/saveContact', '测试95', 'Http Form Data', 'true', 'MD5', NULL, NULL, NULL, NULL);
INSERT INTO "JSDEV"."JS_CARD_ACTION_CONFIG"("ID", "COMPANY_ID", "CMD", "CONFIG", "TPL", "PARAM_TYPE", "STATUS", "INTERFACE_URL", "COMPANY_NAME", "BODY_TYPE", "IS_DATA_SIGN", "SIGN_ALGORITHM", "SIGN_BODY", "CONTAIN_TYPE", "CONTAIN_RULE", "THIRD_PLATFORM") VALUES ('91', '1', 'before', '{
	"enable": "1",
	"isHttps": "0",
	"submit_url": "",
	"oid": "",
	"mKey": "",
	"data": {
		"VISITORSTATICID": "$CARD_STATICID",
		"userRealName": "$CARD_REALNAME",
		"MOBILE": "$CARD_MOBILE",
		"NAME": "$CARD_NAME",
		"QQ": "$CARD_QQ",
		"MSN": "$CARD_WEIXIN",
		"CREATETIME": "$CARD_CREATETIME",
		"ALLOCATIONTIME": "$CARD_ALLOCATIONTIME",
		"CRMSTATE": "$CARD_STATE",
		"subjectName": "$CARD_COLUMN8",
		"areaName": "$CARD_COLUMN9",
		"EXTCOLUMN10": "$CARD_COLUMN10",
		"NOTE": "$CARD_NOTE",
		"EXTCOLUMN1": "$CARD_COLUMN1",
		"RECORDS": "$CARD_RECORDS"
	}
}', '{
	"crmzdy_88232948":"$visitorStaticId",
	"crm_holder":"$userRealName",
	"crmzdy_80974415":"$mobile",
	"crm_name":"$name",
	"crmzdy_80974418":"$qq",
	"crmzdy_88070094":"$weixin",
	"crmzdy_88232342":"$createTime",
	"crmzdy_88232295":"$allocationTime",
	"crmzdy_80979018":"$crmState",
	"crmzdy_81253707":"$subjectName",
	"crmzdy_88167326":"$schoolName",
	"crmzdy_80974439":"$extColumn10",
	"crmzdy_80979020":"$note",
	"crmzdy_88232284":"$createUserId",
	"crmzdy_88232306":"$extColumn1",
	"crmzdy_88232317":"$currentChatDetail",
        "siteId":"$siteId",
        "siteName":"$siteName"
}', 'json', '1', 'http://cn828.800app.com/uploadfile/staticresource/257790/269129/sy_AddLeads.aspxtttt', NULL, 'json', NULL, NULL, NULL, 'indexof', '11111', 'saiyoucrm');
INSERT INTO "JSDEV"."JS_CARD_ACTION_CONFIG"("ID", "COMPANY_ID", "CMD", "CONFIG", "TPL", "PARAM_TYPE", "STATUS", "INTERFACE_URL", "COMPANY_NAME", "BODY_TYPE", "IS_DATA_SIGN", "SIGN_ALGORITHM", "SIGN_BODY", "CONTAIN_TYPE", "CONTAIN_RULE", "THIRD_PLATFORM") VALUES ('5', '90', 'senddata', '{
							"enable": "1",
							"isHttps": "0",
							"submit_url": "",
							"oid": "",
							"mKey": "",
							"data": {
								"VISITORSTATICID": "$CARD_STATICID",
								"REALNAME": "$CARD_REALNAME",
								"MOBILE": "$CARD_MOBILE",
								"NAME": "$CARD_NAME",
								"QQ": "$CARD_QQ",
								"MSN": "$CARD_WEIXIN",
								"CREATETIME": "$CARD_CREATETIME",
								"ALLOCATIONTIME": "$CARD_ALLOCATIONTIME",
								"CRMSTATE": "$CARD_STATE",
								"EXTCOLUMN8": "$CARD_COLUMN8",
								"EXTCOLUMN9": "$CARD_COLUMN9",
								"EXTCOLUMN10": "$CARD_COLUMN10",
								"NOTE": "$CARD_NOTE",
								"EXTCOLUMN1": "$CARD_COLUMN1",
								"RECORDS": "$CARD_RECORDS"
							}
						}
  					', '{
	"staticId": "$CARD_STATICID",
	"crm_holder": "$CARD_REALNAME",
	"crmzdy_80974415": "$CARD_MOBILE",
	"crm_name": "$CARD_NAME",
	"crmzdy_80974418": "$CARD_QQ",
	"crmzdy_88070094": "$CARD_WEIXIN",
	"crmzdy_88232342": "$CARD_CREATETIME",
	"crmzdy_88232295": "$CARD_ALLOCATIONTIME",
	"crmzdy_80979018": "$CARD_STATE",
	"crmzdy_81253707": "$CARD_COLUMN8",
	"crmzdy_88167326": "$CARD_COLUMN9",
	"crmzdy_80974439": "$CARD_COLUMN10",
	"crmzdy_80979020": "$CARD_NOTE",
	"crmzdy_88232306": "$CARD_COLUMN1",
	"crmzdy_88232317": "$CARD_RECORDS"
}', 'json', '0', 'http://cn828.800app.com/uploadfile/staticresource/257790/269129/sy_AddLeads.aspx', '客户90', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
