system:
  domain: http://dbview.easymis.org
  email: 535782704@qq.com
  emailpwd:
  name: easymis
  icp: 蜀ICP备17043811号-1
  auth: www.easymis.org
#server:
#  tomcat:
#    access_log_enabled: true
#    basedir: target/tomcat
spring:
  profiles:
    include: pay,mail,param
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: true
  redis:
      #数据库索引（默认为0）
    database: 10
    host: 118.31.43.2
    password:
    port: 6379
    timeout: 5000
    pool:
      max-active: 8 
      max-idle: 8
      max-wait: -1
  elasticsearch:
    host: 127.0.0.1
    port: 9200
    scheme: http
    pool: 5
    jest:
      uris: http://127.0.0.1:9200
      username: elastic
      password: 123456
      read-timeout: 20000 #读取超时
    connection-timeout: 20000 #连接超时

##多数据源
datasource:
  #主库
  master:
    jdbcUrl: jdbc:mysql://127.0.0.1:3307/easysaas?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #从库
  slave:
    #并非url而是jdbcUrl(因为这个在获取数据源时一直报错，看了DataSource的属性才知道是jdbcUrl)
    jdbcUrl: jdbc:mysql://127.0.0.1:3307/easycompany?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#配置日志
logging:
  #采用相对路径方式将日志文件输出到
    file: log\easymis-dbview.log
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  #配置日志文件路径
    level:
        root: debug
        org.easymis.dbview: debug #不同目录下的日志可配置不同级别
        org.springfromework.web: ERROR
        org.hibernate: error
# 自定义文件上传路径
web:
    upload-path: /home/work/dataview
    image-site: http://image.easymis.org/dbview/
ftp:
    ip: 118.31.43.2
    port: 21
    username: tanyujie
    password: 123456
    remote-base-dir: dbview
    local-base-dir: dbview
swagger2:
  enable: true