server:
  port: 8090
springbootwebfluxjjwt:
  password:
    encoder:
      secret: mysecret
      iteration: 33
      keylength: 256
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave512bitsKeySize
    expiration: 28800
management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
  endpoint:
    bus-refresh:
      enabled: true
spring:
  application:
    name: easysaas-gateway
  security:
    user:
      name: 13551259347
      password: 51c0ceb9087c69fac88fb6c3736d0fe9
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  jmx:
    enabled: false
  redis:
    #数据库索引（默认为0）
    database: 10
    host: 118.31.43.2
    password:
    port: 6379
    timeout: 100
    pool:
      max-active: 8 
      max-idle: 8
      max-wait: -1
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: easysaas-member
        uri: lb://easysaas-member
        predicates:
        - Path=/member/**
        filters:
        - StripPrefix=1
      - id: gateway-security
        uri: lb://gateway-security
        predicates:
        - Path=/api/**
        filters:
        - StripPrefix=1
        
      - id: easysaas-mobile
        uri: lb://easysaas-mobile
        predicates:
        - Path=/mobile/**
      - id: crm_route
        uri: lb://easysaas-crm
        predicates:
        - Path=/crm/**
      - id: xinyue-sever-router
        uri: lb://xinyue-server-a
        order: -1  # 注意这个优先级的问题，因为对于此uri有多个路由器，如果优先级低，不会起作用
        predicates:
        - Path=/xinyue-server-a/account/login  # 拦截登陆请求
        filters:
        - Authentication   # 添加自定义的过滤器
        - name: RewritePath
          args:
            regexp: /xinyue-server-a/(?<remaining>.*)
            replacement: /${remaining}
  zipkin:
    base-url: http://192.168.230.1:9987/
  #这里把抽样百分比设置为1，即信息全部采集
  sleuth:
    sampler:
      probability: 1.0
eureka:
  instance:
    prefer-ip-address: true 
  client:
    register-with-eureka: true 
    fetch-registry: true 
    service-url:
      defaultZone: http://easysass:easysass123@118.31.43.2:8761/eureka #Eureka服务位置
filters:
# 熔断降级配置
- name: Hystrix
  args:
    name : default
    fallbackUri: 'forward:/defaultfallback'
# hystrix 信号量隔离，3秒后自动超时
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 3000
  shareSecurityContext: true
##多数据源
datasource:
  #主库
  master:
    jdbcUrl: jdbc:mysql://127.0.0.1:3307/easysaas?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #从库
  slave:
    #并非url而是jdbcUrl(因为这个在获取数据源时一直报错，看了DataSource的属性才知道是jdbcUrl)
    jdbcUrl: jdbc:mysql://127.0.0.1:3307/easysaas?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
    mapper-locations: classpath*:org/easymis/easysaas/gateway/entitys/mybatis/mapper/*Mapper.xml
    type-aliases-package: org.easymis.easysaas.gateway.modules.entitys.mybatis.dto
    configuration:
        mapUnderscoreToCamelCase: true
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    pageSizeZero: true
    params: count=countSql
swagger2:
  enable: true