spring:
  mail:
    username: huangjinyan@sharepanzer.com
    password: Banza@developer2019
    host: smtp.exmail.qq.com
    port: 587
    default-encoding: utf-8
    protocol: smtp
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 30000
          writetimeout: 10000
          auth: true
          starttls:
            enable: true
          isSSL: true
        socketFactory:
          port: 587
          fallback: false
          class: javax.net.ssl.SSLSocketFactory
    fromMail: huangjinyan@sharepanzer.com
    ## 每次可导出最大值
    perTime: 1000
  messages:
    encoding: UTF-8

